version: '3.3'

services:
 
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: chirag
      MYSQL_PASSWORD: chinmay@77
      MYSQL_ROOT_PASSWORD: chinmay@77
    volumes:
      - db_storage:/var/lib/mysql
  wordpress:
    image: wordpress:5.1.1-php7.3-apache
    restart: mysql:5.7
    depends_on: 
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: chirag
      WORDPRESS_DB_PASSWORD: chinmay@77
      WORDPRESS_DB_NAME: db
    volumes:
      - wp_storage:/var/www/html

volumes:
   wordpress: wp_storage
   db: mysql_storage
