version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: chirag
      WORDPRESS_DB_PASSWORD: chinmay@77
      WORDPRESS_DB_NAME: db
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: cp
      MYSQL_USER: chirag
      MYSQL_PASSWORD: chinmay@77
      MYSQL_RANDOM_ROOT_PASSWORD: chinmay@77
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress: wp_storage
  db: mysql_storage
